In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv("cars.csv")
data.head(10)

,Model,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
1,buick skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
2,plymouth satellite,18.0,8,318.0,150.0,3436.0,11.0,70,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,US
4,ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
5,ford galaxie 500,15.0,8,NaN,198.0,4341.0,10.0,70,US
6,chevrolet impala,14.0,8,454.0,220.0,4354.0,9.0,70,US
7,plymouth fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US
8,pontiac catalina,14.0,8,455.0,225.0,4425.0,10.0,70,USA
9,amc ambassador dpl,15.0,8,390.0,190.0,3850.0,8.5,70,US

In [4]:
data['Origin'].unique()

array(['US', 'USA', 'Japan', 'Europe', 'France', nan], dtype=object)

In [5]:
dit={'US': '100001', 'USA':'100001', 'Japan':'100010', 'Europe':'100100', 'France':'101000'}

In [6]:
data['transformed']=data['Origin'].map(dit)

In [7]:
data

,Model,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Year,Origin,transformed
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US,100001
1,buick skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US,100001
2,plymouth satellite,18.0,8,318.0,150.0,3436.0,11.0,70,USA,100001
3,amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,US,100001
4,ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,US,100001
5,ford galaxie 500,15.0,8,NaN,198.0,4341.0,10.0,70,US,100001
6,chevrolet impala,14.0,8,454.0,220.0,4354.0,9.0,70,US,100001
7,plymouth fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US,100001
8,pontiac catalina,14.0,8,455.0,225.0,4425.0,10.0,70,USA,100001
9,amc ambassador dpl,15.0,8,390.0,190.0,3850.0,8.5,70,US,100001
10,dodge challenger se,15.0,8,383.0,170.0,3563.0,10.0,70,US,100001
11,plymouth 'cuda 340,14.0,8,340.0,160.0,3609.0,8.0,70,US,100001
12,chevrolet monte carlo,15.0,8,400.0,150.0,3761.0,9.5,70,US,100001
13,buick estate wagon (sw),14.0,8,NaN,225.0,3086.0,10.0,70,US,100001
14,toyota corona mark ii,24.0,4,113.0,95.0,2372.0,15.0,70,Japan,100010
15,plymouth duster,22.0,6,198.0,95.0,2833.0,15.5,70,US,100001
16,amc hornet,18.0,6,199.0,97.0,2774.0,15.5,70,US,100001
17,ford maverick,21.0,6,200.0,85.0,2587.0,16.0,70,US,100001
18,datsun pl510,27.0,4,97.0,88.0,2130.0,14.5,70,Japan,100010
19,volkswagen 1131 deluxe sedan,26.0,4,97.0,46.0,1835.0,20.5,70,Europe,100100
20,peugeot 504,25.0,4,110.0,87.0,2672.0,17.5,70,Europe,100100
21,audi 100 ls,24.0,4,107.0,90.0,2430.0,14.5,70,Europe,100100
22,saab 99e,25.0,4,104.0,95.0,2375.0,17.5,70,Europe,100100
23,bmw 2002,26.0,4,121.0,113.0,2234.0,12.5,70,Europe,100100
24,amc gremlin,21.0,6,199.0,90.0,2648.0,15.0,70,US,100001
25,ford f250,10.0,8,360.0,215.0,4615.0,14.0,70,US,100001
26,chevy c20,10.0,8,307.0,200.0,4376.0,15.0,70,US,100001
27,dodge d200,11.0,8,318.0,210.0,4382.0,13.5,70,US,100001
28,hi 1200d,9.0,8,304.0,193.0,4732.0,18.5,70,US,100001
29,datsun pl510,27.0,4,97.0,88.0,2130.0,14.5,71,Japan,100010
...,...,...,...,...,...,...,...,...,...,...
364,chevrolet cavalier wagon,27.0,4,112.0,88.0,2640.0,18.6,82,US,100001
365,chevrolet cavalier 2-door,34.0,4,112.0,88.0,2395.0,18.0,82,US,100001
366,pontiac j2000 se hatchback,31.0,4,112.0,85.0,2575.0,16.2,82,US,100001
367,dodge aries se,29.0,4,135.0,84.0,2525.0,16.0,82,US,100001
368,pontiac phoenix,27.0,4,151.0,90.0,2735.0,18.0,82,US,100001
369,ford fairmont futura,24.0,4,140.0,92.0,2865.0,16.4,82,US,100001
370,amc concord dl,23.0,4,151.0,NaN,3035.0,20.5,82,US,100001
371,volkswagen rabbit l,36.0,4,105.0,74.0,1980.0,15.3,82,Europe,100100
372,mazda glc custom l,37.0,4,91.0,68.0,2025.0,18.2,82,Japan,100010
373,mazda glc custom,31.0,4,91.0,68.0,1970.0,17.6,82,Japan,100010
374,plymouth horizon miser,38.0,4,105.0,63.0,2125.0,14.7,82,US,100001
375,mercury lynx l,36.0,4,98.0,70.0,2125.0,17.3,82,US,100001
376,nissan stanza xe,36.0,4,120.0,88.0,2160.0,14.5,82,Japan,100010
377,honda accord,36.0,4,107.0,75.0,2205.0,14.5,82,Japan,100010
378,toyota corolla,34.0,4,108.0,70.0,2245.0,16.9,82,Japan,100010
379,honda civic,38.0,4,91.0,67.0,1965.0,15.0,82,Japan,100010
380,honda civic (auto),32.0,4,91.0,67.0,1965.0,15.7,82,Japan,100010
381,datsun 310 gx,38.0,4,91.0,67.0,1995.0,16.2,82,Japan,100010
382,buick century limited,25.0,6,181.0,110.0,2945.0,16.4,82,US,100001
383,oldsmobile cutlass ciera (diesel),38.0,6,262.0,85.0,3015.0,17.0,82,US,100001
384,chrysler lebaron medallion,26.0,4,156.0,92.0,2585.0,14.5,82,US,100001
385,ford granada l,22.0,6,232.0,112.0,2835.0,14.7,82,US,100001
386,toyota celica gt,32.0,4,144.0,96.0,2665.0,13.9,82,Japan,100010
387,dodge charger 2.2,36.0,4,135.0,84.0,2370.0,13.0,82,US,100001
388,chevrolet camaro,27.0,4,151.0,90.0,2950.0,17.3,82,US,100001
389,ford mustang gl,27.0,4,140.0,86.0,2790.0,15.6,82,US,100001
390,vw pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe,100100
391,dodge rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US,100001
392,ford ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US,100001
393,chevy s-10,31.0,4,119.0,82.0,2720.0,19.4,82,US,100001